
lane :create_icons do
    appicon(
        # 'appicon_image_file' defaults to "fastlane/metadata/app_icon.png" <- base 1024px icon saved there
        appicon_devices: [:iphone, :ipad, :ios_marketing],
        appicon_path: 'TwitterTrends/SupportFiles/Assets.xcassets'
    )
end
